### ISSUE TITLE
Zombie orchestra

### ISSUE THREAD

**Issue by ZXQWAS** [iChun/Clef#12]
If I put some named zombies with instruments together, would they play in 1 band? I'd also like to be able to join them, say give a band name "Orchestra" by default to all zombies playing an instrument. This is probably a feature request, but maybe this is possible somehow already? I don't mean the instrument player, I mean a live performance.

**Comment by iChun** [comment]
If I recall correctly, all zombies play together in a band called "zombies"

**Comment by iChun** [comment]
However, them starting a song is purely random and others joining in is purely random as well.
