### ISSUE TITLE
NPE crash when disconnecting from Multiplayer server

### ISSUE THREAD

**Issue by dsmall3303** [iChun/Clef#13]
When disconnecting from a multiplayer server, I get a null pointer exception. I am unsure if the issue is with Clef or with VanillaFix, as VanillaFix generates a screen where you can get the crashlog. When clicking the "Back to Main Menu" button, the game seems to loop back to the same crash.

Crash report:
VanillaFix was used to capture the crash
https://paste.dimdev.org/uwocahihih.mccrash

Minecraft version: 1.12.2
Forge version: 14.23.4.2750 
Clef version: 7.0.0
iChunUtil version: 7.1.4 
VanillaFix version: 1.0.9-97 

see also https://github.com/DimensionalDevelopment/VanillaFix/issues/115

**Comment by ichttt** [comment]
Should be fixed by #11
