### ISSUE TITLE
Anti Aliasing Crash with Clef

### ISSUE THREAD

**Issue by DorkyMcDorkus** [iChun/Clef#16]
Whenever I enable anti-aliasing and try to view a Clef instrument, the game crashes. This took a really long time to find the cause of, but I am 99% sure the cause of the crash is enabling anti-aliasing with Optifine. For example, I will load into a world, open the creative menu and search guitar. The second a Clef item comes into viewing the game will crash. Any ideas to fix it, or is this a bug?

Crash --> https://pastebin.com/aFrU2sjk

**Comment by heldplayer** [comment]
Interesting that it crashes without it mentioning either Optifine or Clef in the stack trace, but that it crashes while it's rendering a Clef item in the crash report.

This looks like it's either a bug in Optifine or Clef, or there's an edge case with the way both interact with each other. Does the crash occur if you've only got Optifine and Clef installed?

I'm also noticing that the stack trace is missing the actual exception that got raised (`NullPointerException` or something similar ending in `Exception`, optionally followed by a message, right before the actual stack trace). I think this would help in finding out what's going wrong.

**Comment by iChun** [comment]
Yeah that's the first question on my mind as well, can the crash be
isolated to AA being on with Clef?

Clef does do something a little special with item renders but from what I
understand if the crash can be isolated to having Optifine around then the
issue should be addressed on their end. There are some edge cases of
course.

**Comment by DorkyMcDorkus** [comment]
I think its just an optifine issue. I tried to run shaders and the game crashed too, and I have a computer more than capable of running them. Hopefully they'll sort it out in a newer release.
