### ISSUE TITLE
Random Freezes

### ISSUE THREAD

**Issue by Autissima** [iChun/Clef#2]
I play on a server and we randomly freeze in different songs, I once let it stay frozen and the server didn't time me out, but the game was still frozen. This happened in different songs, was not really reproducable. Tried songs with speed changes, wrong notations, wrong characters etc. nothing froze us consistently. Sometimes we don't even freeze all. Only one of us.

**Comment by ScruffyRules** [comment]
> **Certain instrument sounds can freeze the game**
>Minecraft's Sound System doesn't play very nicely sometimes with sound files that it doesn't understand. Because of the way the mod works, there potentially are some files that could cause the game to freeze (servers will remain fine). I don't have a way to detect this. Try and identify which instrument causes this and avoid using the instrument. Such as the drumkit. Especially the drumkit. Fur Elise freezes the game on this. Use this information as you will.

[Source](https://minecraft.curseforge.com/projects/clef)

**Comment by Autissima** [comment]
Yes, but we couldn't find any consistences, trying to avoid the drumkit from now on. Thank you anyways :)

**Comment by iChun** [comment]
Please let me know if the it's not the drumkit that causes this. It only froze the game on my system so I don't know if it's the same with everyone else. I'm still not sure how I would like to handle sounds that would potentially freeze the game because I know there are some mod sounds that freezes the game.

**Comment by Autissima** [comment]
It happens randomly, on nearly every instrument. At first we thought it was the high pitch microphone. But it became less frequent over time, and happened to different amounts of players. Sometimes all in vicinity, some times only one or two.

**Comment by Autissima** [comment]
I am not at home right now. I can test it thoroughly tomorrow or today in the evening.

**Comment by ZXQWAS** [comment]
I provided somewhat more info at http://www.minecraftforge.net/forum/topic/65012-paulscodesoundsoundsystemcommandqueue-client-hangup-lwjgl3-in-1122-please/
It might be a good idea to have zombie spawn with instruments turned off by default.
