### ISSUE TITLE
[1.16.3] Server hard lock on player uploading a song.

### ISSUE THREAD

**Issue by ProsperCraft** [iChun/Clef#24]
Server log with stacktrace at the bottom-
https://gist.github.com/ProsperCraft/1a3d3295f3c037b89f730dd1e3ce4b27

Here is the file that was uploaded through the players client.

[Smash_Mouth_-_All_Star_Lyric.zip](https://github.com/iChun/Clef/files/5319462/Smash_Mouth_-_All_Star_Lyric.zip)

**Comment by ProsperCraft** [comment]
Players did it again-
https://gist.github.com/ProsperCraft/e2275b8509f192bca4fa5dbb725c5268

**Comment by iChun** [comment]
Fixed build out: 10.0.1. Thanks @ichttt for fix.
