### ISSUE TITLE
Songs require 2 plays for other players to hear it.

### ISSUE THREAD

**Issue by ajlittle** [iChun/Clef#27]
on the latest 1.16 build, if the other player does not have the song received already, it requires 2 plays from the person/mob/block who has it for the person to hear it instead of 1.

**Comment by ichttt** [comment]
Should be fixed with 10.0.2, grab it here https://www.curseforge.com/minecraft/mc-mods/clef/files/3224926
Please reopen the ticket when the issue still exists

**Comment by drakosoldier298** [comment]
Seems this issue has returned on 10.1.0 on 1.16.5
